package com.vault.sync.service;

import com.vault.sync.entity.Credential;
import com.vault.sync.repository.CredentialRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Objects;

@Service
public class CredentialService {
    private final CredentialRepository credentialRepository;

    @Autowired
    public CredentialService(CredentialRepository _credentialRepository){
        this.credentialRepository = _credentialRepository;
    }

    public Credential createCredential(Credential credential){
        credential.setId(null); // Autogenerated ID
        return credentialRepository.save(credential);
    }

    public boolean existsById(Long id){
        return credentialRepository.existsById(id);
    }

    public boolean checkCredBelongsToUser(List<Long> credIds, String username){
        List<Credential> credentials = credentialRepository.findAllById(credIds);
        for(Credential c : credentials){
            if(!Objects.equals(c.getOwner(), username)) return false;
        }

        return true;
    }
}
