-- ==========================================================
-- Table Definitions
-- ==========================================================

-- 1. Vault User
CREATE TABLE IF NOT EXISTS vault_user (
    username VARCHAR(255) PRIMARY KEY,
    password VARCHAR(255) NOT NULL
);

-- 2. Device
CREATE TABLE IF NOT EXISTS device (
    id VARCHAR(255) PRIMARY KEY,
    owner VARCHAR(255) NOT NULL,
    public_key TEXT,
    CONSTRAINT fk_device_owner
        FOREIGN KEY (owner)
            REFERENCES vault_user(username)
            ON DELETE CASCADE
);

-- 3. Credential
CREATE TABLE IF NOT EXISTS credential (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner VARCHAR(255) NOT NULL,
    CONSTRAINT fk_credential_owner
        FOREIGN KEY (owner)
            REFERENCES vault_user(username)
            ON DELETE CASCADE
);

-- 4. Shared Credential
CREATE TABLE IF NOT EXISTS shared_credential (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner VARCHAR(255) NOT NULL,
    CONSTRAINT fk_shared_credential_owner
        FOREIGN KEY (owner)
            REFERENCES vault_user(username)
            ON DELETE CASCADE
);

-- 5. Sync Item
CREATE TABLE IF NOT EXISTS sync_item (
    device_id VARCHAR(255) NOT NULL,
    credential_id BIGINT NOT NULL,
    content TEXT,
    PRIMARY KEY (device_id, credential_id),
    CONSTRAINT fk_sync_item_device
        FOREIGN KEY (device_id)
            REFERENCES device(id)
            ON DELETE CASCADE,
    CONSTRAINT fk_sync_item_credential
        FOREIGN KEY (credential_id)
            REFERENCES credential(id)
            ON DELETE CASCADE
);

-- 6. Share Item
CREATE TABLE IF NOT EXISTS share_item (
    device_id VARCHAR(255) NOT NULL,
    shared_cred_id BIGINT NOT NULL,
    content TEXT,
    PRIMARY KEY (device_id, shared_cred_id),
    CONSTRAINT fk_share_item_device
        FOREIGN KEY (device_id)
            REFERENCES device(id)
            ON DELETE CASCADE,
    CONSTRAINT fk_share_item_shared_credential
        FOREIGN KEY (shared_cred_id)
            REFERENCES shared_credential(id)
            ON DELETE CASCADE
);

-- ==========================================================
-- Indexes
-- ==========================================================

CREATE INDEX IF NOT EXISTS idx_device_owner ON device(owner);
CREATE INDEX IF NOT EXISTS idx_credential_owner ON credential(owner);
CREATE INDEX IF NOT EXISTS idx_shared_credential_owner ON shared_credential(owner);
CREATE INDEX IF NOT EXISTS idx_sync_item_credential_id ON sync_item(credential_id);
CREATE INDEX IF NOT EXISTS idx_share_item_shared_cred_id ON share_item(shared_cred_id);

-- ==========================================================
-- Orphan Cleanup Triggers
-- ==========================================================

-- Trigger — sync_item → credential

CREATE OR REPLACE FUNCTION cleanup_credential_if_orphaned()
RETURNS TRIGGER AS $$
DECLARE
    remaining_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO remaining_count
    FROM sync_item
    WHERE credential_id = OLD.credential_id;

    IF remaining_count = 0 THEN
        DELETE FROM credential WHERE id = OLD.credential_id;
    END IF;

    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_cleanup_credential_after_sync_item_delete ON sync_item;

CREATE TRIGGER trg_cleanup_credential_after_sync_item_delete
    AFTER DELETE ON sync_item
    FOR EACH ROW
    EXECUTE FUNCTION cleanup_credential_if_orphaned();


-- Trigger — share_item → shared_credential

CREATE OR REPLACE FUNCTION cleanup_shared_credential_if_orphaned()
RETURNS TRIGGER AS $$
DECLARE
    remaining_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO remaining_count
    FROM share_item
    WHERE shared_cred_id = OLD.shared_cred_id;

    IF remaining_count = 0 THEN
        DELETE FROM shared_credential WHERE id = OLD.shared_cred_id;
    END IF;

    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_cleanup_shared_credential_after_share_item_delete ON share_item;

CREATE TRIGGER trg_cleanup_shared_credential_after_share_item_delete
    AFTER DELETE ON share_item
    FOR EACH ROW
    EXECUTE FUNCTION cleanup_shared_credential_if_orphaned();
